# Generated by Django 5.0.7 on 2024-07-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="GameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=20)),
                ("score", models.IntegerField()),
                ("players", models.ManyToManyField(to="gamingApp.playermodel")),
            ],
        ),
    ]
